import { ConservationProject } from "@/types";

export const FEATURED_PROJECT: ConservationProject = {
  id: "prj-42",
  code: "PRJ-42",
  title: "Lake Restoration Project #42",
  interventionType: "Lake Rejuvenation",
  state: "Karnataka",
  district: "Ramanagara / Kanakapura Basin",
  coordinates: {
    lat: 12.548,
    lng: 77.421,
  },
  status: "needs_attention",
  impactScore: 68,
  baseline: {
    projectId: "prj-42",
    projectName: "Lake Restoration Project #42",
    observationPeriod: "Pre-Intervention Baseline (Oct 2023 - Jan 2024)",
    sensor: "Sentinel-2 MSI (10m Resolution) + Landsat-8 Thermal",
    resolution: "10-meter spatial ground resolution",
    baselineCaptureDate: "15 Jan 2024",
    cloudCoverPercent: 1.2,
    preInterventionNotes: "Siltation along eastern feeder channel, fragmented shoreline vegetation, depleted dry-season water body extent.",
    metrics: {
      ndvi: 0.42,
      ndwi: 0.31,
      waterExtentHa: 12.4,
      vegetationCoveragePercent: 68,
      surfaceTempCelsius: 28.4,
      bsi: 0.22,
    },
  },
  governance: {
    probableCostCr: 2.4,
    fundsAllocatedCr: 2.4,
    fundsUtilizedCr: 1.7, // 71%
    utilizationPercent: 71,
    department: "Department of Minor Irrigation & Groundwater Resources (Karnataka)",
    scheme: "Mission Amrit Sarovar / National Plan for Aquatic Ecosystems (NPCA)",
    environmentalProgressPercent: 53,
    integrityStatus: "Review Recommended",
    integrityRemarks: "Funds utilization at 71% while environmental trajectory is lagging at 53% target recovery. Anomaly flagged for human field verification.",
  },
  monitoringTimeline: [
    {
      milestone: "Day 0",
      date: "Jan 2024",
      waterExtentHa: 12.4,
      vegetationCoveragePercent: 68,
      ndvi: 0.42,
      ndwi: 0.31,
      statusLabel: "Pre-Intervention",
      changeDescription: "Baseline condition: Severe silt accumulation in northern inlet; seasonal drying evident.",
      satelliteThumbnailDesc: "Dry silt sediment bed, low aquatic reflectance",
      anomalyScore: 0.05,
    },
    {
      milestone: "Month 1",
      date: "Feb 2024",
      waterExtentHa: 13.8,
      vegetationCoveragePercent: 70,
      ndvi: 0.44,
      ndwi: 0.34,
      statusLabel: "Initial Excavation",
      changeDescription: "Initial desilting begun; slight pooling recorded in central reservoir basin.",
      satelliteThumbnailDesc: "Active earthworks, modest turbidity increase",
      anomalyScore: 0.12,
    },
    {
      milestone: "Month 3",
      date: "Apr 2024",
      waterExtentHa: 15.6,
      vegetationCoveragePercent: 72,
      ndvi: 0.47,
      ndwi: 0.39,
      statusLabel: "Early Inflow",
      changeDescription: "Weir restoration complete; water holding capacity improving steadily.",
      satelliteThumbnailDesc: "Continuous water boundary established",
      anomalyScore: 0.18,
    },
    {
      milestone: "Month 6",
      date: "Jul 2024",
      waterExtentHa: 17.2,
      vegetationCoveragePercent: 75,
      ndvi: 0.51,
      ndwi: 0.42,
      statusLabel: "Trajectory Slowdown",
      changeDescription: "Vegetation greening on bunds, but water persistence plateauing below seasonal monsoon model.",
      satelliteThumbnailDesc: "Patchy weed resurgence in eastern quadrant",
      anomalyScore: 0.42,
    },
    {
      milestone: "Month 12",
      date: "Jan 2025",
      waterExtentHa: 18.1,
      vegetationCoveragePercent: 77,
      ndvi: 0.53,
      ndwi: 0.45,
      statusLabel: "Needs Attention",
      changeDescription: "Water extent 18.1 ha vs expected 24.5 ha. Inflow blockage identified on northern feeder canal.",
      satelliteThumbnailDesc: "Deficit in expected high-water boundary line",
      anomalyScore: 0.65,
    },
  ],
  trajectory: [
    { month: "Month 1", monthNum: 1, expected: 20, actual: 18, upperConfidence: 22, lowerConfidence: 16, rainfallAnomalyMm: +4 },
    { month: "Month 3", monthNum: 3, expected: 38, actual: 32, upperConfidence: 42, lowerConfidence: 34, rainfallAnomalyMm: -8 },
    { month: "Month 6", monthNum: 6, expected: 60, actual: 48, upperConfidence: 65, lowerConfidence: 55, rainfallAnomalyMm: +12 },
    { month: "Month 9", monthNum: 9, expected: 78, actual: 55, upperConfidence: 84, lowerConfidence: 72, rainfallAnomalyMm: -2 },
    { month: "Month 12", monthNum: 12, expected: 90, actual: 61, upperConfidence: 96, lowerConfidence: 84, rainfallAnomalyMm: +5 },
  ],
  healthIndicators: [
    {
      name: "Water Recovery",
      category: "Water",
      status: "stable",
      value: "18.1 ha",
      trend: "stable",
      description: "Water extent has stabilized but remains 26% below hydrological carrying capacity model.",
    },
    {
      name: "Vegetation Health",
      category: "Vegetation",
      status: "improving",
      value: "NDVI 0.53",
      trend: "up",
      description: "Riparian buffer planting along southern bund demonstrates healthy chlorophyll absorption.",
    },
    {
      name: "Recovery Trajectory",
      category: "Trajectory",
      status: "stagnating",
      value: "-18% Deviation",
      trend: "down",
      description: "Trajectory divergence expanded over Q3-Q4 due to feeder canal sediment choke point.",
    },
    {
      name: "Rainfall Context",
      category: "Climate",
      status: "improving",
      value: "+5mm Anomaly",
      trend: "stable",
      description: "Local precipitation patterns are within normal historical monsoon decile (not drought-induced).",
    },
  ],
  failurePrediction: {
    projectId: "prj-42",
    failureRiskPercent: 32,
    riskLevel: "Moderate",
    predictionStatement: "Early trajectory variance indicates potential underperformance if current conditions continue.",
    projectedTimelineWeeks: 8,
    confidenceScorePercent: 89,
    factors: [
      {
        factor: "Trajectory Deviation from Ecological Target",
        impactWeight: 38,
        direction: "negative",
        evidence: "Actual recovery curve is 29 points behind Month 12 baseline projection of 90.",
        category: "hydrology",
      },
      {
        factor: "Reduced Water Persistence in Feeder Sector",
        impactWeight: 27,
        direction: "negative",
        evidence: "Temporal NDWI indicates drying rates 1.6x faster than natural percolation in sector C-2.",
        category: "hydrology",
      },
      {
        factor: "Riparian Vegetation Recovery Rate Slowing",
        impactWeight: 21,
        direction: "negative",
        evidence: "NDVI delta flattened between Month 6 (+0.04) and Month 12 (+0.02).",
        category: "vegetation",
      },
      {
        factor: "Regional Rainfall Normalization Context",
        impactWeight: 14,
        direction: "neutral",
        evidence: "Precipitation is normal; ruling out regional drought as the primary causal factor.",
        category: "climate",
      },
    ],
  },
};

export const ALL_PROJECTS: ConservationProject[] = [
  FEATURED_PROJECT,
  {
    id: "prj-18",
    code: "PRJ-18",
    title: "Chambal Ravine Eco-Restoration",
    interventionType: "Afforestation & Forest Restoration",
    state: "Madhya Pradesh",
    district: "Morena",
    coordinates: { lat: 26.495, lng: 77.994 },
    status: "improving",
    impactScore: 88,
    baseline: {
      projectId: "prj-18",
      projectName: "Chambal Ravine Eco-Restoration",
      observationPeriod: "Pre-Restoration Baseline (2023)",
      sensor: "Sentinel-2 MSI 10m",
      resolution: "10m",
      baselineCaptureDate: "10 Aug 2023",
      cloudCoverPercent: 2.0,
      preInterventionNotes: "Severe gully erosion, loss of topsoil, native babool scrub loss.",
      metrics: {
        ndvi: 0.28,
        ndwi: 0.08,
        waterExtentHa: 3.2,
        vegetationCoveragePercent: 32,
      },
    },
    governance: {
      probableCostCr: 4.8,
      fundsAllocatedCr: 4.8,
      fundsUtilizedCr: 4.3,
      utilizationPercent: 90,
      department: "State Forest Department & Soil Conservation Board",
      scheme: "Green India Mission (GIM)",
      environmentalProgressPercent: 86,
      integrityStatus: "Normal Progress",
      integrityRemarks: "Strong correlation between tree canopy density and ground check data.",
    },
    monitoringTimeline: [],
    trajectory: [
      { month: "Month 1", monthNum: 1, expected: 15, actual: 16, upperConfidence: 18, lowerConfidence: 12, rainfallAnomalyMm: 0 },
      { month: "Month 3", monthNum: 3, expected: 35, actual: 36, upperConfidence: 40, lowerConfidence: 30, rainfallAnomalyMm: 5 },
      { month: "Month 6", monthNum: 6, expected: 58, actual: 61, upperConfidence: 64, lowerConfidence: 52, rainfallAnomalyMm: 10 },
      { month: "Month 9", monthNum: 9, expected: 75, actual: 79, upperConfidence: 82, lowerConfidence: 68, rainfallAnomalyMm: -2 },
      { month: "Month 12", monthNum: 12, expected: 88, actual: 91, upperConfidence: 94, lowerConfidence: 82, rainfallAnomalyMm: 1 },
    ],
    healthIndicators: [],
    failurePrediction: {
      projectId: "prj-18",
      failureRiskPercent: 9,
      riskLevel: "Low",
      predictionStatement: "Canopy density and soil retention bunds tracking ahead of model benchmarks.",
      projectedTimelineWeeks: 12,
      confidenceScorePercent: 94,
      factors: [],
    },
  },
  {
    id: "prj-29",
    code: "PRJ-29",
    title: "Thar Dune Stabilization & Grassland",
    interventionType: "Grassland Restoration",
    state: "Rajasthan",
    district: "Jaisalmer / Pokhran Belt",
    coordinates: { lat: 26.915, lng: 71.912 },
    status: "stable",
    impactScore: 74,
    baseline: {
      projectId: "prj-29",
      projectName: "Thar Dune Stabilization & Grassland",
      observationPeriod: "Pre-Intervention 2023",
      sensor: "Sentinel-2 MSI + Landsat-9",
      resolution: "10m",
      baselineCaptureDate: "05 Nov 2023",
      cloudCoverPercent: 0.1,
      preInterventionNotes: "Shifting sand encroachment, degradation of sewan grass cover.",
      metrics: {
        ndvi: 0.14,
        ndwi: 0.02,
        waterExtentHa: 0.8,
        vegetationCoveragePercent: 18,
      },
    },
    governance: {
      probableCostCr: 3.1,
      fundsAllocatedCr: 3.1,
      fundsUtilizedCr: 2.0,
      utilizationPercent: 64,
      department: "Desert Development Cell & Pasture Board",
      scheme: "National Mission on Sustainable Agriculture (NMSA)",
      environmentalProgressPercent: 70,
      integrityStatus: "Normal Progress",
      integrityRemarks: "Micro-fencing successfully prevented grazing during germination.",
    },
    monitoringTimeline: [],
    trajectory: [],
    healthIndicators: [],
    failurePrediction: {
      projectId: "prj-29",
      failureRiskPercent: 22,
      riskLevel: "Low",
      predictionStatement: "Grassland biomass shows resilient moisture retention despite arid winds.",
      projectedTimelineWeeks: 10,
      confidenceScorePercent: 88,
      factors: [],
    },
  },
  {
    id: "prj-55",
    code: "PRJ-55",
    title: "Sundarbans Tidal Mangrove Regeneration",
    interventionType: "Mangrove Conservation",
    state: "West Bengal",
    district: "South 24 Parganas",
    coordinates: { lat: 21.949, lng: 88.899 },
    status: "improving",
    impactScore: 82,
    baseline: {
      projectId: "prj-55",
      projectName: "Sundarbans Tidal Mangrove Regeneration",
      observationPeriod: "2023 Post-Cyclone Assessment",
      sensor: "Sentinel-1 SAR + Sentinel-2 MSI",
      resolution: "10m",
      baselineCaptureDate: "20 Oct 2023",
      cloudCoverPercent: 3.4,
      preInterventionNotes: "Embankment erosion, saline water inundation, sapling loss.",
      metrics: {
        ndvi: 0.58,
        ndwi: 0.65,
        waterExtentHa: 45.0,
        vegetationCoveragePercent: 54,
      },
    },
    governance: {
      probableCostCr: 5.2,
      fundsAllocatedCr: 5.2,
      fundsUtilizedCr: 4.1,
      utilizationPercent: 78,
      department: "Sundarban Affairs Department & Mangrove Cell",
      scheme: "MISHTI (Mangrove Initiative for Shoreline Habitats)",
      environmentalProgressPercent: 80,
      integrityStatus: "Normal Progress",
      integrityRemarks: "Rhizophora survival rate exceeds 82% across high tidal zones.",
    },
    monitoringTimeline: [],
    trajectory: [],
    healthIndicators: [],
    failurePrediction: {
      projectId: "prj-55",
      failureRiskPercent: 15,
      riskLevel: "Low",
      predictionStatement: "Dense root architecture established along mudflats.",
      projectedTimelineWeeks: 16,
      confidenceScorePercent: 91,
      factors: [],
    },
  },
  {
    id: "prj-63",
    code: "PRJ-63",
    title: "Sahyadri Ridge Micro-Watershed",
    interventionType: "Watershed Management",
    state: "Maharashtra",
    district: "Pune / Western Ghats",
    coordinates: { lat: 18.618, lng: 73.541 },
    status: "stagnating",
    impactScore: 59,
    baseline: {
      projectId: "prj-63",
      projectName: "Sahyadri Ridge Micro-Watershed",
      observationPeriod: "Pre-Monsoon 2024",
      sensor: "Sentinel-2 MSI 10m",
      resolution: "10m",
      baselineCaptureDate: "12 May 2024",
      cloudCoverPercent: 0.8,
      preInterventionNotes: "Runoff velocity causing steep slope erosion, check-dam siltation.",
      metrics: {
        ndvi: 0.45,
        ndwi: 0.22,
        waterExtentHa: 8.5,
        vegetationCoveragePercent: 62,
      },
    },
    governance: {
      probableCostCr: 1.9,
      fundsAllocatedCr: 1.9,
      fundsUtilizedCr: 1.6,
      utilizationPercent: 84,
      department: "Water Conservation Department (Maharashtra)",
      scheme: "Jalyukt Shivar Abhiyan 2.0",
      environmentalProgressPercent: 51,
      integrityStatus: "Review Recommended",
      integrityRemarks: "High expenditure recorded but continuous contour trenches (CCT) show uneven maintenance.",
    },
    monitoringTimeline: [],
    trajectory: [],
    healthIndicators: [],
    failurePrediction: {
      projectId: "prj-63",
      failureRiskPercent: 44,
      riskLevel: "Moderate",
      predictionStatement: "Erosion mitigation works underperforming due to unseasonal cloudburst events.",
      projectedTimelineWeeks: 6,
      confidenceScorePercent: 85,
      factors: [],
    },
  },
  {
    id: "prj-71",
    code: "PRJ-71",
    title: "Chilika Lagoon Fringe Wetland Revival",
    interventionType: "Wetland Ecosystem Revitalization",
    state: "Odisha",
    district: "Puri",
    coordinates: { lat: 19.725, lng: 85.312 },
    status: "underperforming",
    impactScore: 44,
    baseline: {
      projectId: "prj-71",
      projectName: "Chilika Lagoon Fringe Wetland Revival",
      observationPeriod: "Post-Monsoon 2023",
      sensor: "Sentinel-2 MSI 10m + PlanetScope",
      resolution: "10m",
      baselineCaptureDate: "18 Nov 2023",
      cloudCoverPercent: 1.9,
      preInterventionNotes: "Invasive macrophytes (Eichhornia) smothering brackish migratory bird habitat.",
      metrics: {
        ndvi: 0.69,
        ndwi: 0.48,
        waterExtentHa: 38.0,
        vegetationCoveragePercent: 84,
      },
    },
    governance: {
      probableCostCr: 3.6,
      fundsAllocatedCr: 3.6,
      fundsUtilizedCr: 3.2,
      utilizationPercent: 89,
      department: "Chilika Development Authority (CDA)",
      scheme: "National Coastal Mission (NCM)",
      environmentalProgressPercent: 39,
      integrityStatus: "Inconsistency Flagged",
      integrityRemarks: "Expenditure booked for weed de-infestation, yet multi-temporal NDVI shows weed regrowth within 45 days.",
    },
    monitoringTimeline: [],
    trajectory: [],
    healthIndicators: [],
    failurePrediction: {
      projectId: "prj-71",
      failureRiskPercent: 68,
      riskLevel: "High",
      predictionStatement: "High risk of total weed re-infestation unless mechanical de-weeding frequency is doubled.",
      projectedTimelineWeeks: 4,
      confidenceScorePercent: 92,
      factors: [],
    },
  },
  {
    id: "prj-84",
    code: "PRJ-84",
    title: "Aravalli Biodiversity Corridors",
    interventionType: "Afforestation & Forest Restoration",
    state: "Haryana",
    district: "Gurugram / Faridabad Ridge",
    coordinates: { lat: 28.384, lng: 77.089 },
    status: "insufficient_data",
    impactScore: 51,
    baseline: {
      projectId: "prj-84",
      projectName: "Aravalli Biodiversity Corridors",
      observationPeriod: "Recent Inception (Q4 2024)",
      sensor: "Sentinel-2 MSI 10m",
      resolution: "10m",
      baselineCaptureDate: "02 Dec 2024",
      cloudCoverPercent: 4.1,
      preInterventionNotes: "Mining scar remediation, native dhau tree seed-ball dispersal.",
      metrics: {
        ndvi: 0.31,
        ndwi: 0.05,
        waterExtentHa: 1.1,
        vegetationCoveragePercent: 29,
      },
    },
    governance: {
      probableCostCr: 2.0,
      fundsAllocatedCr: 2.0,
      fundsUtilizedCr: 0.7,
      utilizationPercent: 35,
      department: "Haryana Forest Department & Aravalli Green Wall Cell",
      scheme: "Aravalli Green Wall Project",
      environmentalProgressPercent: 30,
      integrityStatus: "Normal Progress",
      integrityRemarks: "Recent onboarding; baseline validated, awaiting second-quarter overpass imagery.",
    },
    monitoringTimeline: [],
    trajectory: [],
    healthIndicators: [],
    failurePrediction: {
      projectId: "prj-84",
      failureRiskPercent: 25,
      riskLevel: "Low",
      predictionStatement: "Awaiting high-resolution post-monsoon pass to confirm germination rate.",
      projectedTimelineWeeks: 14,
      confidenceScorePercent: 70,
      factors: [],
    },
  },
];

export const MOCK_COPILOT_QUERIES = [
  {
    question: "Why is Project #42 underperforming?",
    response:
      "Project #42 (Lake Restoration Project #42, Ramanagara) is currently 18% below its expected Month 9 recovery trajectory (actual recovery score: 55 vs expected: 78). Sentinel-2 multi-spectral time-series data confirms that while southern bund vegetation has improved (NDVI +0.11), surface water persistence in the northern basin has declined by 26%. Satellite telemetry in quadrant C-2 isolates an unmitigated sediment choke point along the primary feeder canal.",
    citations: [
      {
        id: "cit-1",
        title: "Sentinel-2 MSI Multi-Temporal Water Extent Analysis (Dec 2024)",
        source: "Satellite Telemetry" as const,
        timestamp: "Overpass: 2024-12-18",
        snippet: "NDWI reflectance dropped from 0.42 to 0.38 in inlet zone; water boundary contracted 3.1 hectares.",
      },
      {
        id: "cit-2",
        title: "Mission Amrit Sarovar Desilting & Buffer Standard v3.2",
        source: "MoEFCC Guideline" as const,
        timestamp: "Section 4.1 - Inflow Integrity",
        snippet: "Feeder canals must maintain unrestricted gradient with minimum 30m vegetated buffer zone.",
      },
      {
        id: "cit-3",
        title: "State Minor Irrigation Department Expenditure Ledger Q3",
        source: "State Budget Record" as const,
        timestamp: "Booked: 2024-11-04",
        snippet: "Funds utilized 71% (₹1.7 Cr of ₹2.4 Cr allocated). Desilting contractor milestone 3 cleared.",
      },
    ],
    followups: [
      "What corrective actions does the AI engine recommend for Project #42?",
      "Compare Project #42 with similar lake rejuvenation projects in Karnataka.",
      "Generate an evidence summary for the District Collector.",
    ],
  },
  {
    question: "What MoEFCC guidelines apply to wetland buffer zones?",
    response:
      "Under the Wetlands (Conservation and Management) Rules and NPCA statutory guidelines, wetland conservation projects must enforce a 50-meter non-development peripheral eco-buffer. Satellite-derived Bare Soil Index (BSI) and NDVI boundary tracing can automatically audit whether agricultural or construction encroachments are penetrating this mandated perimeter.",
    citations: [
      {
        id: "cit-4",
        title: "Wetlands (Conservation and Management) Rules, 2017",
        source: "MoEFCC Guideline" as const,
        timestamp: "Rule 4(2)(vi)",
        snippet: "Prohibits any construction of a permanent nature not directly beneficial to wetland ecology.",
      },
    ],
    followups: [
      "Run automated buffer encroachment audit across all Karnataka lake projects.",
      "Which active projects have flagged buffer zone degradation?",
    ],
  },
  {
    question: "Show fund allocation efficiency for Karnataka watershed projects.",
    response:
      "Across 14 active monitored interventions in Karnataka under NPCA and Watershed Development: Average fund utilization is 74.2%, with an average environmental recovery score of 69.4. Project #42 shows the highest utilization-to-recovery discrepancy (71% funds utilized vs 53% target recovery achieved), warranting a physical ground audit.",
    citations: [
      {
        id: "cit-5",
        title: "Integrated Governance & Environmental Outcome Matrix 2024-25",
        source: "State Budget Record" as const,
        timestamp: "Audit Period: FY 24-25",
        snippet: "Karnataka State Minor Irrigation aggregate expenditure reports ₹34.8 Cr disbursed.",
      },
    ],
    followups: [
      "Export state-level financial vs environmental integrity table.",
      "Schedule drone verification for Project #42.",
    ],
  },
];

export function getAllProjects(): ConservationProject[] {
  return ALL_PROJECTS;
}

export function getProjectById(id: string): ConservationProject {
  const found = ALL_PROJECTS.find(
    (p) => p.id.toLowerCase() === id.toLowerCase() || p.code.toLowerCase() === id.toLowerCase()
  );
  if (!found) return FEATURED_PROJECT;
  
  return {
    ...FEATURED_PROJECT,
    ...found,
    baseline: {
      ...FEATURED_PROJECT.baseline,
      ...found.baseline,
      projectName: found.title,
      projectId: found.id,
    },
    governance: {
      ...FEATURED_PROJECT.governance,
      ...found.governance,
    },
    monitoringTimeline: found.monitoringTimeline && found.monitoringTimeline.length > 0
      ? found.monitoringTimeline 
      : FEATURED_PROJECT.monitoringTimeline,
    trajectory: found.trajectory && found.trajectory.length > 0 
      ? found.trajectory 
      : FEATURED_PROJECT.trajectory,
    healthIndicators: found.healthIndicators && found.healthIndicators.length > 0 
      ? found.healthIndicators 
      : FEATURED_PROJECT.healthIndicators,
    failurePrediction: found.failurePrediction && found.failurePrediction.factors && found.failurePrediction.factors.length > 0
      ? found.failurePrediction
      : {
          ...FEATURED_PROJECT.failurePrediction,
          ...found.failurePrediction,
        },
  };
}
